### PR TITLE
Optimize metrics calls via tagging

### PR DESCRIPTION
**Pull request by robhudson**
Using tags to add data and letting the metric name be less specific. With this approach we can select the metric and group by the tags to show charts in Grafana.

A nice example from socorro:
https://earthangel-b40313e5.influxcloud.net/d/LysVjx8Zk/socorro-prod-megamaster-remix?orgId=1&refresh=1m&from=now-6h&to=now&viewPanel=100

### CODE REVIEW

**Comment by pmac** [comment]
This all looks good. A question came up recently about whether a change had affected the rate at which people subscribed to a particular newsletter. Is it possible with tagging to add the newsletter ID to subscription stats?

**Comment by robhudson** [comment]
> This all looks good. A question came up recently about whether a change had affected the rate at which people subscribed to a particular newsletter. Is it possible with tagging to add the newsletter ID to subscription stats?

Yes! I like that. We can definitely have a successfully subscribed metric and have the newsletter ID as a tag so we can filter or group by them.

**Comment by pmac** [comment]
Great! Wanna do that as a follow-up or add it to this PR?

**Review by pmac — APPROVED** [review]
👍

**Comment by robhudson** [comment]
> Great! Wanna do that as a follow-up or add it to this PR?

Follow-up commit. I took a quick look. It's a bit more complex since there's multiple newsletters and they could be subscribing or updating their subscriptions or even unsubscribing, and it happens in a task. And we're just asking CTMS to update the records but we can still signal a metric to show we requested it.

**Pull request merged**
