### PR TITLE
Bug 1302820: Add a subscribe endpoint for use with frontent code

### PR DESCRIPTION
**Pull request by pmac**

### CODE REVIEW

**Comment by pmac** [comment]
@glogiotatidis r?

**Comment by glogiotatidis** [comment]
hopefully by tomorrow, sorry for the delay pmac

**Comment by glogiotatidis** [comment]
Hey @pmac  I'm swamped with SUMO migration work, I don't have a date for this one atm. If this can wait, I'm happy to review at some point, otherwise please ping someone else. Apologies :|

**Comment by pmac** [comment]
No worries @glogiotatidis. Thanks for the note though. I'll ping someone else if I have to. I have other priorities at the moment as well.

**Comment by pmac** [comment]
@glogiotatidis just bringing this one back up again. I've cleaned it up and rebased, so I think it's ready for a look finally. No rush still, but I would like to get it in and start testing in the Real World™️.

**Comment by pmac** [comment]
Took another look. Seems okay and mostly affects a new and unused API endpoint.

Self r+

**Pull request merged**
