### PR TITLE
Handle TypeError when field value is None. Fix #195

### LINKED ISSUE #195: None value throwing errors in sfdc.py/to_vendor
Appears to be similar to #193. Changes to MoFo are impacting collecting subscriptions.

Specific error is [this line in sfdc.py in the `to_vendor` method](https://github.com/mozmeao/basket/blob/prod/basket/news/backends/sfdc.py#L165):

`if field in contact and len(contact[field]) > length:`

Error thrown is: `TypeError: object of type 'NoneType' has no len()`

Sentry shows `FirstName` has a value of `None`.

Error report is [here](https://sentry.prod.mozaws.net/operations/basket-prod/issues/5947191/).

### PR DESCRIPTION
**Pull request by jgmize**
#195

### CODE REVIEW

**Comment by metadave** [comment]
+1, are there any tests that cover this fix?

**Comment by pmac** [comment]
we should add a test for this issue. I'll add one to this branch quickly and then merge. thanks!

**Comment by pmac** [comment]
@jgmize I added tests, and as part of that changed how it was fixed. Based on how we handle blank values I think those keys with None values should be filtered out entirely, so I've done it that way instead. Let me know what you think.

**Comment by jgmize** [comment]
Thanks @pmac, this is much better than my quick fix was.

**Pull request merged**
