### PR TITLE
Updating the Request to CTMS when Empty Newsletter w/ Optout

### PR DESCRIPTION
**Pull request by bsieber-mozilla**

### CODE REVIEW

**Comment by bsieber-mozilla** [comment]
#Adding test scenario
In this commit I added a scenario that currently is not working in the system.

#Updating Conditional
In this commit I've updated the conditional to capture this additional scenario.

**Comment by bsieber-mozilla** [comment]
#Updating value at time of conditional
To ensure that the unsubscribe was being provided, when not seen in new test (valid?) scenario.

#Moving optout check to before newsletter check 
Moved the conditional to before checking for existence of newsletters.

**Review by jwhitlock — APPROVED** [review]
Thanks @bsieber-mozilla, I appreciate the targeted test

**Comment by bsieber-mozilla** [comment]
👍 wfm; the added test might not be valid if the request to optout always
came with a newsletter object.

**Pull request closed without merging**
