### PR TITLE
Switch to official Salesforce FuelSDK libraries

### LINKED ISSUE #98: Upgrade FuelSDK
https://pypi.org/project/Salesforce-FuelSDK/

This also includes an upgrade to the suds library.

### PR DESCRIPTION
**Pull request by pmac**
Fix #98

### CODE REVIEW

**Comment by jgmize** [comment]
needs rebase but other than that looking good so far; pulling down locally for testing

**Comment by pmac** [comment]
Yeah. I think it needs some more investigation and testing, but so far so good. Mostly wanted circle to run, but Github is having issues with that at present.

**Comment by pmac** [comment]
We were using my fork of the Fuel-SDK library because of some shortcomings of the official library. It looks like we're going to have to continue doing that. I was installing from my personal fork, but I'll fork it in `mozmeao` and install from there.

**Comment by pmac** [comment]
Okay. I think this is ready for a full test and review.

**Pull request merged**
